/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OmMigRouteImport } from './routes/om-mig'
import { Route as MinTilgangRouteImport } from './routes/min-tilgang'
import { Route as IndexRouteImport } from './routes/index'

const OmMigRoute = OmMigRouteImport.update({
  id: '/om-mig',
  path: '/om-mig',
  getParentRoute: () => rootRouteImport,
} as any)
const MinTilgangRoute = MinTilgangRouteImport.update({
  id: '/min-tilgang',
  path: '/min-tilgang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/min-tilgang': typeof MinTilgangRoute
  '/om-mig': typeof OmMigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/min-tilgang': typeof MinTilgangRoute
  '/om-mig': typeof OmMigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/min-tilgang': typeof MinTilgangRoute
  '/om-mig': typeof OmMigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/min-tilgang' | '/om-mig'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/min-tilgang' | '/om-mig'
  id: '__root__' | '/' | '/min-tilgang' | '/om-mig'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinTilgangRoute: typeof MinTilgangRoute
  OmMigRoute: typeof OmMigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/om-mig': {
      id: '/om-mig'
      path: '/om-mig'
      fullPath: '/om-mig'
      preLoaderRoute: typeof OmMigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/min-tilgang': {
      id: '/min-tilgang'
      path: '/min-tilgang'
      fullPath: '/min-tilgang'
      preLoaderRoute: typeof MinTilgangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinTilgangRoute: MinTilgangRoute,
  OmMigRoute: OmMigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
